### ISSUE TITLE
Instagram icon

### ISSUE THREAD

**Issue by vieron** [drinchev/monosocialiconsfont#3]
Would be nice to have the Instagram logo: http://instagram-static.s3.amazonaws.com/images/instagram-glyph.zip

Btw, great icon font. Thanks for sharing!

**Comment by drinchev** [comment]
Fixed in version 1.10 https://github.com/drinchev/monosocialiconsfont/commit/e3ad9be016132f1e2711bf41370bf1fa63ba3833

**Comment by vieron** [comment]
Thanks!
